Repository realponto-project/alxa-log-web, pull requests merged in 2021-09, with the labels that each got.

#143 chore: add new values on formIncident, tableIncident and filterIncident
  src/Components/Filters/Incident.js
  src/Containers/Driver/Detail/IncidentForm/formSettings.js
  src/Containers/Driver/Detail/IncidentList/index.js
  src/constants/Driver/index.js
Labels: alxa-log, front

#144 add feed back message
  src/Pages/MaintenanceOrder/Manager/index.js
  src/Pages/Mobile/MaintenanceDetailMobile/index.js
Labels: bug, enhancement, alxa-log, front

#142 Incidents driver edit
  src/Containers/Driver/Detail/IncidentForm/index.js
  src/Containers/Driver/Detail/IncidentList/index.js
  src/Containers/Driver/Detail/index.js
  src/Pages/Driver/Detail/index.js
  src/Services/Driver/index.js
Labels: enhancement, good first issue, alxa-log, front

#145 fix: order on detail maintenance
  src/Containers/Maintenance/Detail/index.js
Labels: bug, alxa-log

#146 feat: date filter on home page
  src/Containers/Home/index.js
  src/Pages/Home/index.js
  src/Services/Summary/index.js
  src/index.css
Labels: enhancement, alxa-log, front

#172 chore: update driver expire dates
  src/Containers/Driver/DriverForm/updateDates.js
  src/Containers/Driver/Manager/DriverList/index.js
  src/Containers/Driver/Manager/index.js
Labels: alxa-log, front

#176 Update expire dates
  src/Components/circleBar/index.js
  src/Containers/Driver/DriverForm/updateDates.js
  src/Containers/Driver/Manager/DriverList/index.js
  src/Pages/Driver/Manager/index.js
Labels: alxa-log, front

#177 chore: add serial number on vehicle
  src/Containers/Vehicle/Detail/ModalAddSerialNumber/index.js
  src/Containers/Vehicle/Detail/index.js
  src/Pages/Vehicle/Detail/index.js
Labels: alxa-log, front

#181 many changes
  src/Containers/Branch/Detail/index.js
  src/Containers/MyTeam/Manager/MyTeamList/index.js
  src/Containers/MyTeam/Manager/index.js
  src/Containers/MyTeam/MyTeamForm/formSettings.js
  src/Containers/MyTeam/MyTeamForm/index.js
  src/Containers/Operation/Detail/index.js
  src/Pages/MyTeam/Manager/index.js
  src/Services/Company/index.js
Labels: alxa-log, front

#183 No clear forms
  src/Containers/Driver/DriverForm/index.js
  src/Containers/Driver/Manager/index.js
  src/Containers/Maintenance/MaintenanceForm/index.js
  src/Containers/Maintenance/Manager/index.js
  src/Pages/Driver/Manager/index.js
  src/Pages/MaintenanceOrder/Manager/index.js
Labels: bug, alxa-log, front
